### PR TITLE
use deps-regex

### PR DESCRIPTION
**Pull request by mathieudutour**
I am now using the plugin pattern, returning a array of dependencies from the parser.

There is still one test failing which i'm still unsure where it comes from:  
screen shot 2015-10-16 at 17 31 00

### CODE REVIEW

**Comment by lijunle** [comment]
The test case failed because it finds dependencies on the `depend` function calls.

In general, we grab `require` function calls to get the dependent packages. However, user can use other function calls to define dependencies, and user can opt-in their logic by themselvies. 

In this particular test case, it find dependencies from `depend` function calls and ignore the original `require` function calls from AST. Deps-regex only report the packages for `require` function calls, so it fails on this test case.

I agree that, this is a rare corner case. However, I think we should still support it in native JavaScript file.

**Comment by mathieudutour** [comment]
Oh I get it. But then it's incompatible with all parsers returning just the array of dependencies right?

**Comment by lijunle** [comment]
No, only this test case ignore the `require` function calls.

In regards to this RP, consider a known issue https://github.com/mathieudutour/deps-regex/issues/1 from deps-regex, we could **not** touch the existing ES6 and JSX parser, but introduce deps-regex for CoffeeScript parser. If someone report issues related to the known issue, we have a chance to "fix" it.

**Comment by mathieudutour** [comment]
Agree. I will personally use deps-regex for everything as having the trade-off between false positive and performance is worth it in my case. Feel free to close this PR.

**Comment by lijunle** [comment]
OK. Could you like to send another RP to implement CoffeeScript parser with deps-regex?

**Pull request closed without merging**
