### PR TITLE
Test case to cover invoke require with nothing.

### PR DESCRIPTION
**Pull request by lijunle**
- Increase branch test coverage to [**100.0%**](https://travis-ci.org/lijunle/depcheck-es6/jobs/81291902#L139) :100:

### CODE REVIEW

**Comment by woodb** [comment]
Wow, amazing! Nice!

**Comment by woodb** [comment]
That's going to make coveralls very hard to please :) I like it

**Comment by lijunle** [comment]
Actually, the bin/depcheck.js is not covered.

I have some plan to (hugely) modify the source code. It is a good practice to add tests to cover everything first. :smile:

**Comment by woodb** [comment]
> It is a good practice to add tests to cover everything first. :smile:

My thoughts exactly :+1: I'm always weary to do major rewrites w/out having that in place first, so this is great.

**Pull request merged**
